### ISSUE TITLE
Is it still works?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [zaufi/npm2ebuild#1]

**Comment by zaufi** [comment]
Unlikely ;-(Back in the days I was using Gentoo I found that it was not possible to make it work for all packages due to the weird nature of the `npm` package manager simulator. So, I had stopped with this...
Nowadays I change Gentoo to Exherbo %)

**Comment by vitaly-zdanevich** [comment]
Why Exherbo is better?

**Comment by zaufi** [comment]
> Why Exherbo is better?

Everybody decided for themselves why... for me the choice was obvious (and mindfulness). I left Gentoo for the sake of Exherbo around 6 years ago and never regretted it! Feel very much satisfied and happy ;) Exherbo is the best distro ever for me :)

PS Was a Gentoo user for about 16 years…

**Comment by vitaly-zdanevich** [comment]
> for me the choice was obvious (and mindfulness)

Please explain, this is interesting. Exherbo looks like much less supported.

**Comment by zaufi** [comment]
What kind of support you have asked for and from whom? %)

**Comment by vitaly-zdanevich** [comment]
Just interesting why to switch from Gentoo to Exherbo

**Comment by zaufi** [comment]
Because Exherbo is a way better fit for me than Gentoo.
